# Generated by Django 3.0.5 on 2020-12-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droids', '0002_peca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='preco',
        ),
        migrations.AddField(
            model_name='peca',
            name='urgente',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
