# Generated by Django 3.0.5 on 2020-12-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droids', '0005_auto_20201213_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], default='Aberta', max_length=10)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droids.Anunciante')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droids.Peca')),
            ],
        ),
    ]
