# Generated by Django 3.0.5 on 2020-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droids', '0007_auto_20201213_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
